-- inntoit: RECONSTRUCTED baseline of the Supabase database (public schema + "attachments" bucket).
-- Built by hand from your schema dump of 2026-10-03 plus 0001 to 0003 (so it shows the state AFTER those files).
-- Use it as documentation and to create an empty staging project. It is not a byte-exact dump of production.
-- Items marked (assumed) could not be read from the dump.

-- ---------- tables ----------
create table if not exists public.bookmarks (
  id           bigint generated by default as identity primary key,   -- (assumed: identity column)
  created_at   timestamptz not null default timezone('utc'::text, now()),
  title        text not null,
  url          text not null,
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  category     text default 'Uncategorized',
  sub_category text,
  description  text,
  image_url    text,
  tags         text[] default '{}'::text[],
  type         text default 'link',
  content      text,
  file_path    text,
  file_type    text,
  updated_at   timestamptz not null default now()
);

create table if not exists public.api_keys (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users(id) on delete cascade,
  token      text not null unique,          -- stores a SHA-256 hash, never the raw key
  created_at timestamptz not null default timezone('utc'::text, now())
);

-- ---------- indexes ----------
create unique index if not exists unique_user_link_url
  on public.bookmarks (user_id, url) where (type = 'link' or type is null);
create index if not exists bookmarks_user_created_idx on public.bookmarks (user_id, created_at desc, id desc);
create index if not exists bookmarks_user_category_idx on public.bookmarks (user_id, category, sub_category);
create index if not exists bookmarks_tags_gin_idx on public.bookmarks using gin (tags);

-- ---------- updated_at trigger ----------
create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists bookmarks_set_updated_at on public.bookmarks;
create trigger bookmarks_set_updated_at before update on public.bookmarks
  for each row execute function public.set_updated_at();

-- ---------- row level security ----------
alter table public.bookmarks enable row level security;
alter table public.api_keys enable row level security;

create policy "Users can view their own bookmarks"   on public.bookmarks for select using ((select auth.uid()) = user_id);
create policy "Users can insert their own bookmarks" on public.bookmarks for insert with check ((select auth.uid()) = user_id);
create policy "Users can update their own bookmarks" on public.bookmarks for update using ((select auth.uid()) = user_id);
create policy "Users can delete their own bookmarks" on public.bookmarks for delete using ((select auth.uid()) = user_id);
create policy "Users can manage their own API keys"  on public.api_keys  for all using ((select auth.uid()) = user_id);

-- ---------- realtime ----------
alter publication supabase_realtime add table public.bookmarks;

-- ---------- storage bucket and policies ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('attachments', 'attachments', true, 52428800, array['image/*', 'video/*', 'application/pdf'])
on conflict (id) do nothing;

create policy "attachments: upload to own folder" on storage.objects for insert to authenticated
  with check (bucket_id = 'attachments' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "attachments: read own files" on storage.objects for select to authenticated
  using (bucket_id = 'attachments' and (owner_id = (select auth.uid())::text or (storage.foldername(name))[1] = (select auth.uid())::text));
create policy "attachments: delete own files" on storage.objects for delete to authenticated
  using (bucket_id = 'attachments' and (owner_id = (select auth.uid())::text or (storage.foldername(name))[1] = (select auth.uid())::text));
